MODEL:
  OUTPUT_PATH: "../2-hw/weights/model.pth"
  LR: 1e-3
  EPOCH: 50

DATA:
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]
  RESIZE: [224, 224]
  TRAIN_BATCH_SIZE: 32
  TEST_BATCH_SIZE: 1
  VALIDATION_SIZE: 0.2
  NUM_WORKERS: 4

PATH:
  TRAIN_SET: "./datasets/C1-P1_Train/2"
  TEST_SET: "./datasets/C1-P1_Dev/1"
  DEV_SET: "./datasets/C1-P1_Test/3"
  TRAIN_CSV: "./datasets/train.csv"
  TEST_CSV: "./datasets/dev.csv"
  DEV_CSV: "./datasets/test.csv"

DEVICE:
  GPU: 0
  CUDA: True
